### ISSUE TITLE
LinkedIn social link not working on your live portfolio

### ISSUE THREAD

**Issue by NathanDennis** [mohit01-beep/mohit-portfolio#1]
On your portfolio website, in your social media icon links section, your LinkedIn profile link is trying to link to:
 `https://mohit01-beep.github.io/mohit-portfolio/www.linkedin.com/in/mohit-deshwal-a8703b1a2`

This makes the link redirect to a GitHub 404 Not Found page

Try adding `https://` to your LinkedIn URL on line 41 in `index.html` where you wrote   `<a href="www.linkedin.com/in/mohit-deshwal-a8703b1a2">`

Hope this helps :smile:

**Comment by mohit01-beep** [comment]
Yeah i update the links now ,thanks for letting me know i don't know how i forgot that
